import { rajdhani } from "@/libs/fonts";
import "../styles/globals.css";
import Hero from "@/components/hero/Hero";
import Header from "@/components/header/Header";
import Provider from "./Provider";

export const metadata = {
	title: "Hyalin - Portfolio",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="fr">
			<body className={rajdhani.className}>
				<Provider>
					<Header />
					<div id="home">
						<Hero />
					</div>
					{children}
					{/* Footer */}
				</Provider>
			</body>
		</html>
	);
}
